---
.github/workflows/ci.yaml:
  unit_name: Puppet ${{ matrix.puppet }} (Ruby ${{ matrix.ruby }} fixtures=${{ matrix.fixtures }})
  unit_includes:
    - ruby: '2.4.9'
      puppet: '5'
      fixtures: .fixtures.yml
      allow_failure: false
    - ruby: '2.5.7'
      puppet: '6'
      fixtures: .fixtures-latest.yml
      allow_failure: true
    - ruby: '2.7.0'
      puppet: '7'
      fixtures: .fixtures-latest.yml
      allow_failure: true
  acceptance_matrix:
    set:
      - centos-7
      - centos-8
      - debian-9
      - debian-10
      - ubuntu-1804
    puppet:
      - puppet6
      - puppet7
.travis.yml:
  delete: true
Rakefile:
  changelog_user: tailored-automation
.gitlab-ci.yml:
  delete: true
appveyor.yml:
  delete: true
spec/acceptance/nodesets/centos-6.yml:
  delete: true
spec/acceptance/nodesets/debian-8.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-1604.yml:
  delete: true
